services:
  - type: web
    name: purchase-intent-ml
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 